---
title: "Test_Py_R"
author: "James Lee"
date: "11/30/2020"
output: html_document
---

```{r}
library(reticulate)
use_python("C:/ProgramData/Anaconda3")
original_df <- read.csv("C:/Users/james/Desktop/POLI170 Policy memo/RA_hiring_algorithm/RA_dataset2.csv")

```
 

```{python}
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn import preprocessing

import requests

filepath = 'C:/Users/james/Desktop/POLI170 Policy memo/RA_hiring_algorithm/RA_dataset2.csv'

RA = pd.read_csv(filepath)
print(RA.iloc[:5])

# create subset without categorical values
RA_numeric = RA.drop(['ID', 'race', 'major', 'gender', 'ethnicity'], axis = 1)

# Data normalization is required since each column includes its own value range
# use subset to normalize columns using z-score 
normalized_data = (RA_numeric-RA_numeric.mean())/RA_numeric.std()
normalized_data.head()

#use normalized_data to calculate PCA

# summarize categorical value from original data set
race_count = RA["race"].value_counts().to_frame()
major_count = RA["major"].value_counts().to_frame()
race_count
major_count


```

```{r}

normalized_data <- py$normalized_data
head(normalized_data)

# PCA after normalization 
RA_pca <- prcomp(normalized_data)
summary(RA_pca)
```


```{r}
#biplot (NOT ideal)
biplot(RA_pca)

```

```{r}
# Variance explained by each principal component: pve

pr.var <- RA_pca$sdev^2
pve <- pr.var / sum(pr.var)

# Plot variance explained for each principal component
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")


```


```{r}
# Load the ggplot2 package
library(ggplot2)

pca_df <- as.data.frame(RA_pca$x)

# Make a scatter plot
ggplot(pca_df, aes(x=PC1, y=PC2)) + geom_point(color="red") + theme_bw()


```



```{r}
library(dplyr)

df_cat <- original_df %>%
              select("race", "major", "gender")

df_cat$gender <- as.character(df_cat$gender)
class(df_cat$gender)
df_cat$gender[df_cat$gender=="1"] <- "Female"
df_cat$gender[df_cat$gender=="2"] <- "Male"
df_cat$gender[df_cat$gender=="3"] <- "Non-binary"

pca_df_cat <- merge(pca_df, df_cat, by=0)


#plot again and color by race
ggplot(pca_df_cat, aes(x=PC1, y=PC2, col=race)) + geom_point() + theme_bw() + scale_color_manual(values=c("red", "blue", "green", "black", "grey")) + ggtitle("PCA: PC1 vs PC2 with race indicator")

```




```{r}

#plot again and color by gender
ggplot(pca_df_cat, aes(x=PC2, y=PC3, col=gender)) + geom_point() + theme_bw() + scale_color_manual(values=c("Black", "Purple", "Red")) + ggtitle("PCA: PC2 vs PC3 with gender indicator")


```




```{r}
#plot again and color by race
ggplot(pca_df_cat, aes(x=PC1, y=PC3, col=major)) + geom_point() + theme_bw() + ggtitle("PCA: PC1 vs PC3 with major indicator")


```



 
```{r}
#hypothesis 1: higher gpa = higher score in evaluation
#t.test(df$GPA, df$scoreMean)

#make subset without categorical values
#drops <- c("race", "major")
#df_numeric <- df[, !names(df) %in% drops]


```
 
 